language: scala
scala:
  - 2.10.4
sudo: false
services:
  - mongodb
before_script:
  - echo -e "Host hatu.me\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
  - openssl aes-256-cbc -K $encrypted_b95418a7fb65_key -iv $encrypted_b95418a7fb65_iv -in .travis/aliyun.pem.enc -out .travis/aliyun.pem -d
  - chmod 700 .travis/aliyun.pem
  - eval `ssh-agent -s`; ssh-add .travis/aliyun.pem
  - git remote add deploy ssh://deploy@hatu.me:/home/deploy/deploy/
  - git push deploy master